### ISSUE TITLE
Is everything ok?

### ISSUE THREAD

**Issue by ghost** [FeralAI/PicoFightingBoard#5]
Hello! Just saw that you shut down the shop and nobody is able to reach you. Just not about the Pico FightingBoard but I hope you are ok.

**Comment by sumonado** [comment]
I hope you are ok too! (**+1**)

**Comment by eobet** [comment]
Same!

Both FeralAI and Daemonbite disappeared without a word. I hope it's just supply chain issues and not something else.

**Comment by FeralAI** [comment]
Hello and thank you for your concern. Sorry to have disappeared, I was dealing with health issues. I'm back doing some work on my Github projects and the [GP2040-CE](https://github.com/OpenStickCommunity/GP2040-CE) fork of the original firmware. I will not be reopening the shop but will try get this repository cleaned up and stay active in the community going forward.
